chore: Add test for system certs working

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -116,6 +116,48 @@ jobs:
       run: |
         mv "dist/${{ env.SIMPLE_NAME }}${{ env.RESULT_EXTENSION }}" "${{ env.BUILD_RESULT_NAME }}"
 
+    - name: Test ssl system certs (linux)
+      if: startswith(matrix.os, 'ubuntu')
+      run: |
+        source ${{ env.ACTIVATE_PATH }}
+        certifi_ca_certs="$(python -m certifi)"
+
+        (
+          cd tests/system_certs
+
+          echo 'Print certs' >&2
+          sh print.sh
+
+          echo "Run local https server and ensure it's running" >&2
+          python server.py >/dev/null 2>&1 &
+          sleep 1
+
+          echo 'Ensure certs work as expected' >&2
+          if ! curl --fail --silent https://localhost:12345 --cacert local-ca.pem; then
+            echo 'Failed with local ca!' >&2
+            exit 1
+          fi
+          if curl --fail --silent https://localhost:12345 --cacert "$certifi_ca_certs"; then
+            echo 'Succeeded with certifi ca!' >&2
+            exit 1
+          fi
+
+          echo 'Install certs' >&2
+          sudo cp local-ca.pem /usr/local/share/ca-certificates/local-ca.crt
+          sudo update-ca-certificates
+        )
+
+        # Create placeholder logfile
+        touch latest.log
+
+        echo 'Ensure ssl error is caught when using included certs' >&2
+        echo 'use_included_certs = true' > included_certs_settings.toml
+        "./${{ env.BUILD_RESULT_NAME }}" --test-ssl --settings=included_certs_settings.toml --logfile=latest.log | tee /dev/stderr | grep '^Caught SSLError: ' >/dev/null 2>&1
+
+        echo 'Ensure request succeeds when using system certs' >&2
+        echo 'use_included_certs = false' > system_certs_settings.toml
+        "./${{ env.BUILD_RESULT_NAME }}" --test-ssl --settings=system_certs_settings.toml --logfile=latest.log | tee /dev/stderr | grep '^Got response: Hello world' >/dev/null 2>&1
+
     - name: Upload built binary/app .dmg
       uses: actions/upload-artifact@v4
       with:
