chore: Run ssl test on all OS-es

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -32,6 +32,7 @@ jobs:
         echo 'ACTIVATE_PATH=venv/Scripts/activate' >> $GITHUB_ENV
         echo 'RESULT_EXTENSION=.exe' >> $GITHUB_ENV
         echo 'PYINSTALLER_ARGS=--hide-console=minimize-early' >> $GITHUB_ENV
+        echo 'INSTALL_CA_CERT=certutil.exe -addstore root local-ca.pem' >> $GITHUB_ENV
     - name: OS specific setup (linux)
       if: startswith(matrix.os, 'ubuntu')
       run: |
@@ -39,6 +40,7 @@ jobs:
         echo 'ACTIVATE_PATH=venv/bin/activate' >> $GITHUB_ENV
         echo 'RESULT_EXTENSION=' >> $GITHUB_ENV
         echo 'PYINSTALLER_ARGS=' >> $GITHUB_ENV
+        echo 'INSTALL_CA_CERT=sudo cp local-ca.pem /usr/local/share/ca-certificates/local-ca.crt; sudo update-ca-certificates' >> $GITHUB_ENV
     - name: OS specific setup (mac)
       if: startswith(matrix.os, 'macOS')
       run: |
@@ -49,6 +51,7 @@ jobs:
         # Target universal2 so that the built binary can run on both intel and apple silicon
         # Pass --windowed to build a .app bundle
         echo 'PYINSTALLER_ARGS=--target-architecture universal2 --windowed' >> $GITHUB_ENV
+        echo 'INSTALL_CA_CERT=sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain local-ca.pem' >> $GITHUB_ENV
 
     - name: Select dependency files
       run: |
@@ -111,13 +114,17 @@ jobs:
           "${{ env.BUILD_RESULT_NAME }}" \
           "dist/app/"
 
-    - name: Store built binary (non-mac)
-      if: env.OS_NAME != 'mac'
+    - name: Set binary path
       run: |
-        mv "dist/${{ env.SIMPLE_NAME }}${{ env.RESULT_EXTENSION }}" "${{ env.BUILD_RESULT_NAME }}"
+        echo 'BINARY_PATH="dist/${{ env.SIMPLE_NAME }}${{ env.RESULT_EXTENSION }}"' >> $GITHUB_ENV
 
-    - name: Test ssl system certs (linux)
-      if: startswith(matrix.os, 'ubuntu')
+    - name: Set binary path (mac)
+      if: env.OS_NAME == 'mac'
+      run: |
+        find dist -ls
+        echo 'BINARY_PATH="dist/app/${{ env.SIMPLE_NAME }}.app/"' >> $GITHUB_ENV
+
+    - name: Test ssl system certs
       run: |
         source ${{ env.ACTIVATE_PATH }}
         certifi_ca_certs="$(python -m certifi)"
@@ -133,30 +140,40 @@ jobs:
           sleep 1
 
           echo 'Ensure certs work as expected' >&2
-          if ! curl --fail --silent https://localhost:12345 --cacert local-ca.pem; then
+          # if ! curl --ssl-no-revoke --fail --silent https://localhost:12345 --cacert local-ca.pem; then
+          if ! curl--ssl-no-revoke  https://localhost:12345 --cacert local-ca.pem; then
             echo 'Failed with local ca!' >&2
             exit 1
           fi
-          if curl --fail --silent https://localhost:12345 --cacert "$certifi_ca_certs"; then
+          # if curl --ssl-no-revoke --fail --silent https://localhost:12345 --cacert "$certifi_ca_certs"; then
+          if curl --ssl-no-revoke https://localhost:12345 --cacert "$certifi_ca_certs"; then
             echo 'Succeeded with certifi ca!' >&2
             exit 1
           fi
 
           echo 'Install certs' >&2
-          sudo cp local-ca.pem /usr/local/share/ca-certificates/local-ca.crt
-          sudo update-ca-certificates
+          # sudo cp local-ca.pem /usr/local/share/ca-certificates/local-ca.crt
+          # sudo update-ca-certificates
+          ${{ env.INSTALL_CA_CERT }}
         )
+
+        prism="${{ env.BINARY_PATH }}"
 
         # Create placeholder logfile
         touch latest.log
 
         echo 'Ensure ssl error is caught when using included certs' >&2
         echo 'use_included_certs = true' > included_certs_settings.toml
-        "./${{ env.BUILD_RESULT_NAME }}" --test-ssl --settings=included_certs_settings.toml --logfile=latest.log | tee /dev/stderr | grep '^Caught SSLError: ' >/dev/null 2>&1
+        "$prism" --test-ssl --settings=included_certs_settings.toml --logfile=latest.log | tee /dev/stderr | grep '^Caught SSLError: ' >/dev/null 2>&1
 
         echo 'Ensure request succeeds when using system certs' >&2
         echo 'use_included_certs = false' > system_certs_settings.toml
-        "./${{ env.BUILD_RESULT_NAME }}" --test-ssl --settings=system_certs_settings.toml --logfile=latest.log | tee /dev/stderr | grep '^Got response: Hello world' >/dev/null 2>&1
+        "$prism" --test-ssl --settings=system_certs_settings.toml --logfile=latest.log | tee /dev/stderr | grep '^Got response: Hello world' >/dev/null 2>&1
+
+    - name: Store built binary (non-mac)
+      if: env.OS_NAME != 'mac'
+      run: |
+        mv "dist/${{ env.SIMPLE_NAME }}${{ env.RESULT_EXTENSION }}" "${{ env.BUILD_RESULT_NAME }}"
 
     - name: Upload built binary/app .dmg
       uses: actions/upload-artifact@v4
